# Generated by Django 4.2.5 on 2023-10-04 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_imagesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesetting',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagesetting',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
