# Generated by Django 4.2.5 on 2023-10-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Company Name')),
                ('job_title', models.CharField(blank=True, default='', max_length=120, verbose_name='Job Title')),
                ('job_location', models.CharField(blank=True, default='', max_length=120, verbose_name='Jop Location')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, default='', null=True, verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Experince',
                'verbose_name_plural': 'Experinces',
                'ordering': ('start_date',),
            },
        ),
    ]
