# Generated by Django 4.2.5 on 2023-10-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_experince'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('school_name', models.CharField(blank=True, default='', max_length=120, verbose_name='School Name')),
                ('major', models.CharField(blank=True, default='', max_length=120, verbose_name='Major')),
                ('departman', models.CharField(blank=True, default='', max_length=120, verbose_name='Departman')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, default='', null=True, verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'ordering': ('start_date',),
            },
        ),
    ]
