# Generated by Django 4.2.5 on 2023-10-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Enter Your Name')),
                ('email', models.CharField(blank=True, default='', max_length=255, verbose_name='Enter Email Address')),
                ('subject', models.CharField(blank=True, default='', max_length=255, verbose_name='Enter Subject')),
                ('message', models.TextField(blank=True, default='', max_length=999, verbose_name='Enter Message')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ('-created_date',),
            },
        ),
    ]
